Refactor : Simplify usage of platform by getting rid of platform in the store
epfml/disco pull request #265
Opened 2022-04-07 11:27 UTC by dgengler6

Fixes #262 

**What this does ?**
- Remove the Federated/Decentralized split in platform
- Remove platform from the store and leaves it up to the training manager 
- Added both `Train Federated` and `Train Decentralized` buttons to the training frame
- The client is created when one of these options is chosen
- Remove platform switch button in settings

2022-04-07 11:28 UTC, dgengler6 commented
There is still a reference to the platform in the store because it is used for TaskCreationForm, we can change this I am just not sure what is the use of that there.

2022-04-07 13:02 UTC, martinjaggi commented
thanks for doing this, this will make things simpler indeed.

while you're already doing it, you could simplify even more, we actually don't need any UI element.
you could just add a boolean field to the task config (each task will be predefined either federated or decentralized). 

the reason is that we don't want to allow that people join the same task in potentially different modes. if both modes are wanted people should create 2 separate tasks, one federated one decentralized

2022-04-07 13:15 UTC, Nacho114 commented
> thanks for doing this, this will make things simpler indeed.
> 
> while you're already doing it, you could simplify even more, we actually don't need any UI element. you could just add a boolean field to the task config (each task will be predefined either federated or decentralized).
> 
> the reason is that we don't want to allow that people join the same task in potentially different modes. if both modes are wanted people should create 2 separate tasks, one federated one decentralized

I agree, but there are different ways to implement this, might be good to brainstorm together. The training scheme choice is an important part of Disco so it's good to spend some time discussing on how it is being offered to the user.

2022-04-07 16:51 UTC, dgengler6 commented
So last push changed quite a lot. 

- Now we only have one I18n (i.e default.json) which actually corresponds to the english locale
- the platform directory is now called locales for obvious reasons
- I renamed trainingType into trainingSchemes and moved it in the training folder
- Fully removed any reference to store.getters.platform

2022-04-08 07:41 UTC, Nacho114 commented
You can also add in the description that it fixes #243, that issue was in regards to cleaning i18n which is done here.

2022-04-08 07:44 UTC, Nacho114 commented on mobile-browser-based-version/src/components/building_frames/containers/TrainingFrame.vue
> +            @click="training_manager.joinTraining(decentralizedScheme)"
@s314cy @dgengler6  maybe we could add:

joinFederatedTraining(), joinDecentralizedTraining(), joinLocalTraining(), into the training manager, that way we don't pass arguments and it's resolved in the training_manager?

2022-04-08 12:30 UTC, martinjaggi commented
thanks!
BTW the vue components where we join training maybe don't even need to know if it's federated or not.

it could be figured out later in `training_manager`. so instead of `training_manager.joinFederatedTraining()` one could just make a `training_manager.joinTraining()` and that one would then look at the task config so it would know what to join (federated or decentralized). training alone is different and has it's own button as usual

2022-04-08 12:40 UTC, Nacho114 commented
> thanks! BTW the vue components where we join training maybe don't even need to know if it's federated or not.
> 
> it could be figured out later in `training_manager`. so instead of `training_manager.joinFederatedTraining()` one could just make a `training_manager.joinTraining()` and that one would then look at the task config so it would know what to join (federated or decentralized). training alone is different and has it's own button as usual

yeah i agree, each component should know as little as possible 👍🏼

2022-04-08 14:05 UTC, dgengler6 commented
Done, Although I think we should be clear that we should be clear about what is happening under the hood somewhere (i.e the toast alerts) 
Tbh I don't know if having two times the same task, but one Federated and one Decentralized makes much sense, it might just be confusing for the user..

2022-04-08 16:20 UTC, Nacho114 commented
> Done, Although I think we should be clear that we should be clear about what is happening under the hood somewhere (i.e the toast alerts) Tbh I don't know if having two times the same task, but one Federated and one Decentralized makes much sense, it might just be confusing for the user..

hmm yeah, UI design is not obvious, we can have a discussion on Tuesday -- but keeping it simple is a good rule of thumb, although what simple means is what's hard to figure out

2022-04-28 09:20 UTC, dgengler6 commented
I think I managed to merge everything with the new architecture ! 

Some tests don't pass but I'll fix that asap, It might have smthg to do with the training errors we had.

2022-04-28 09:53 UTC, s314cy commented
looking really nice! on a side note, the `activePage` store has been removed on the current develop version, as the components now communicate between each other instead

would you like to meet with @Nacho114 and me to ensure the CI tests are successful on your next commit?

2022-04-28 11:13 UTC, dgengler6 commented
> looking really nice! on a side note, the `activePage` store has been removed on the current develop version, as the components now communicate between each other instead
> 
> would you like to meet with @Nacho114 and me to ensure the CI tests are successful on your next commit?

Yeah we can meet a bit later this afternoon !

2022-04-28 15:09 UTC, Nacho114 requested changes
Nice work :)

I tried it out but there is an issue with the stop button not appearing after starting training. Once this is fix we will rebase it with devdelop!

2022-04-29 07:25 UTC, Nacho114 approved these changes
Great simplification, good work :)

2022-04-29 07:25 UTC, merged

2022-04-29 07:29 UTC, martinjaggi commented
thanks a lot @dgengler6 !