Ready for v2.0.0
epfml/disco pull request #483
Opened 2022-10-11 15:12 UTC by s314cy

2022-10-19 10:32 UTC, morganridel requested changes

2022-10-19 10:32 UTC, morganridel commented on discojs/package.json
> +    "@epfml/discojs-node": "file:./discojs-node",
Can we move this to devDependencies? If it's used only in test it doesn't need to be here

2022-10-19 10:32 UTC, morganridel commented on discojs/publish.ts
> +  .delete('@epfml/discojs-node')
Also don't need to remove it if it's inside devDependencies

2022-10-20 12:05 UTC, s314cy commented
the CI passes; next step, update the docs :)

2022-10-20 12:26 UTC, morganridel approved these changes
LGTM minus the docs! hoping that the tinkering with symlinks and prepublish won't bite us later

2022-10-20 12:33 UTC, martinjaggi commented
nice! is this PR already causing the release or can we first test some more on the dev branch once it's merged?

2022-10-20 12:48 UTC, s314cy commented
> nice! is this PR already causing the release or can we first test some more on the dev branch once it's merged?

the trigger for the npm publication is to make a github release, so we can merge this with dev and publish later :)

2022-10-24 22:03 UTC, merged