Uploading folder and csv file in training and validation phases
epfml/disco pull request #509
Opened 2022-10-29 10:03 UTC by francesco98

### Discojs library
Added dependency to d3 package

### Web-Client
Updating DatasetInput, IconCard, FileSelection components for allowing CSV and folder upload.

2022-10-29 10:13 UTC, francesco98 commented
I have issues with WRTC on MAC M1, so I cannot correctly update the `package-lock.json`. @s314cy could you please pull the branch and update the file accordingly? Thank you!

2022-10-30 11:18 UTC, francesco98 commented
No idea why `test-lib-core` is failing. @s314cy Do you have any idea?

2022-10-31 08:08 UTC, martinjaggi approved these changes

2022-10-31 09:57 UTC, s314cy requested changes
excellent work, the UI/UX is on point! 🚀 

regarding the ability of discojs to read labels from a separate .csv file, it would be nice to have the functionality available within the lib directly, not only in the web client

this is why, in my opinion, the code handling the csv read and passing the labels to the dataset builder should be included in the data loader/dataset builder code _directly_

I can help you integrate this to the adequate classes, if you need any help!

2022-10-31 09:57 UTC, s314cy commented on web-client/src/components/data/dataset_input/FileSelection.vue
> +console.log(props.isDirectory)
here too :p

2022-10-31 09:57 UTC, s314cy commented on web-client/src/components/data/dataset_input/DatasetInput.vue
> +  console.log(props.datasetBuilder.size())
don't forget to remove the dev console logs :)

2022-10-31 10:03 UTC, s314cy commented on discojs/package.json
> +    "d3": "^7.6.1",
following my code review, it's actually relevant that you added d3 to `discojs`'s dependencies, although your current code would only require the dependency within `web-client`

2022-10-31 14:14 UTC, closed without merging