wip: improve server API for later publishing
epfml/disco pull request #531
Opened 2022-11-03 16:21 UTC by morganridel

2022-11-04 15:34 UTC, s314cy commented
since the server did not provide an API beforehand, we can consider this a feature addition for v2.1.0 :)

2022-11-09 11:24 UTC, morganridel commented
> since the server did not provide an API beforehand, we can consider this a feature addition for v2.1.0 :)
> 
> this means v2.1.0 will include a `@epfml/disco-server` NPM package, as well as the discojs libs bumped to v2.1.0, wdyt?

Yes, however the setup of publishing the server will be done in another PR, this just update the code

2022-11-09 11:30 UTC, s314cy requested changes
awesome work :)

just a tiny detail, the current naming convention would require to rename `discojs-core/src/default-tasks` to `discojs-core/src/default_tasks`, since the middle-dash is reserved to project names whereas modules use lower_dash naming

2022-11-09 11:59 UTC, martinjaggi commented
in the PR description or issue could you describe a bit in more details what you want the API to support (now and in the future?).

also between the server readme and task.md there seems to be a bit of parallels but they don't link to each other or explain which one is for what purpose. try to start the two docs with the user need (who is it for, what will they get out of it if they follow each readme).

note for decentralized, we might aim that a single server should ideally be enough (still everyone should be able to propose new tasks there).  this would be the most common use case. no new server needed then if someone wants to add a new task, right?
while for federated, yes some people in special cases want to run their own server.

2022-11-09 15:45 UTC, s314cy commented
> in the PR description or issue could you describe a bit in more details what you want the API to support (now and in the future?).
>
> also between the server readme and task.md there seems to be a bit of parallels but they don't link to each other or explain which one is for what purpose. try to start the two docs with the user need (who is it for, what will they get out of it if they follow each readme).

The server docs are outdated, so I'll update them to clearly state the server's HTTP endpoints and how to use the provided NPM package (the API brought in this PR).

> note for decentralized, we might aim that a single server should ideally be enough (still everyone should be able to propose new tasks there). this would be the most common use case. no new server needed then if someone wants to add a new task, right? while for federated, yes some people in special cases want to run their own server.

Currently, the discojs lib doesn't provide any API for pushing new tasks to the server in a programmatic way. This is only available in the web client via the task creation form, which pushes to the correct HTTP endpoint of the server—which supports this.

What this PR brings is an API to add new tasks to the server in a programmatic way **as the server host**, which is independent of users pushing new tasks.

2022-11-10 15:03 UTC, s314cy approved these changes

2022-11-10 16:01 UTC, s314cy commented on server/package.json
> +  "version": "2.0.0",
2.1.0 right?

2022-11-10 16:02 UTC, s314cy commented on server/package.json
> +  "version": "2.0.0",
also, maybe we can already bump the version in @epfml/discojs and @epfml/discojs-node already

2022-11-10 16:11 UTC, merged