Basic Testing for Discojs
epfml/disco pull request #697
Opened 2024-07-11 18:54 UTC by josh-freeman

2024-07-12 12:38 UTC, tharvik requested changes
thanks for the contribution! some stuff to iron out, I hope that the remarks will help.

you didn't explicitly ask for a review but your PR wasn't in draft so I though I'll take a look
btw, the branch name is not following [our guidelines](https://github.com/epfml/disco/blob/develop/docs/CONTRIBUTING.md#1-creating-a-new-branch), its format is `$issue-$description-in-very-few-workd-$username`

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +    });
yeah, no need to test for that, aggregator would need to be redone at some point and avoiding to have any reference to the task or the model will be the first thing

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +import { mock, instance, when, anything } from 'ts-mockito';
hum, discojs is still using mocha/chai but if we want new features not present in theses, we will rather move to [vitest](https://vitest.dev/) (already used in the webapp & discojs-node) which provides mocking, parallel testing, good typescript support, …
that said, after the other comments, I don't think you'll even need "ts-mockito" anymore

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +
that's not needed (and is being shown as very red in my `git diff`).

we don't enforce a formatter [yet](https://github.com/epfml/disco/issues/631) but I'm all for slowly moving to prettier (that is, when you add changes, prettify it around, but not the whole file if you only changed a line). I'm hopeful that the transition will be smoother this way.

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +    it("is not full when created with more than no nodes and empty", () => {
```suggestion
    it("is empty when without contributions", () => {
```

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +    it("is full when enough contributions", () => {
```suggestion
    it("is full with enough contributions", () => {
```

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +
ws

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +
whitespaces

```suggestion
```

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +
too much whitespaces
```suggestion
```

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +    it("does not move forward with not enough contributions", async () => {
double negation are hard on my brain. it also feels as a duplicate of the previous one. you can merge the two and check that it didn't advance with only two clients contributions but does with three.

2024-07-12 12:38 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +    it("Adding at the wrong round does not count", () => {
reads more nicely. also, you can keep the test itself smaller by not having three clients but only one. less code == faster to understand => less bug.

```suggestion
    it("drops contributions for futur rounds", () => {
```

2024-07-12 12:38 UTC, tharvik commented on package.json
> +    "ts-mockito": "^2.6.1"
the root package.json is hardly ever changed, especially for dev deps used in a single package. I use it for syncing version of dependencies that are needed across many packages.
please modify discojs/package.json if you want to add a package for discojs. (which you probably don't need as stated previously)

2024-07-12 12:38 UTC, tharvik commented on discojs/src/weights/aggregation.spec.ts
> +  })
this is a bench test, you can simplify it by using a `Set(…).forEach((op) => …)`

while at it, should it fail? an addition without value can be zero, a multiplication can be one; why is this test needed?

```suggestion
  Set.of(aggregation.avg, aggregation.sum, aggregation.diff).forEach((op) => {
    it(`${op.name} of weights with no operands throws`, () =>
      expect(() => op([])).to.throw());

    it(`${op.name} of weights with different dimensions throws`, () =>
      expect(() => op([[[1, 2]], [[3, 4, 5]]])).to.throw());
  });
```

2024-07-15 20:30 UTC, josh-freeman commented on discojs/src/aggregator.spec.ts
> +    });
thank you. It's the first time I work on GitHub with PRs that are not made by cloning for a PR. Should I make a new branch from this branch for the PR?

2024-07-16 13:30 UTC, tharvik commented on discojs/src/aggregator.spec.ts
> +    });
I'm not sure that I follow you: this is already a PR, you can added changes by pushing new commits to the same branch ("test_components") and it'll show up here.

2025-07-08 13:28 UTC, closed without merging

2025-07-08 13:28 UTC, tharvik commented
aggregators where redo recently so outdated