Fix decentralized learning fail
epfml/disco pull request #708
Opened 2024-07-16 17:05 UTC by JulienVig

* Improve the aggregator's logic
* Fix the displayed number of participants in federated and decentralized learning. Closes #707

2024-07-22 10:24 UTC, tharvik requested changes
great work on making decentralized work in browser! :tada:

a few logic/safety errors to fix and it can be merged :+1:

2024-07-22 10:24 UTC, tharvik commented on discojs/src/aggregator/get.ts
> +  }
default arguments behave in the same way

```suggestion
  options: AggregatorOptions = {}): aggregator.Aggregator {
```

2024-07-22 10:24 UTC, tharvik commented on discojs/src/aggregator/get.ts
> +export function getAggregator(task: Task, scheme?: Required<Task['trainingInformation']['scheme']>,
why not having the scheme inside the options argument? it is not required anyway

2024-07-22 10:24 UTC, tharvik commented on discojs/src/aggregator/get.ts
> +  thresholdType?: 'relative' | 'absolute', // MeanAggregator
typescript trick: you can use [`Partial`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) to have an object without all it's field as optional.

2024-07-22 10:24 UTC, tharvik commented on discojs/src/aggregator/get.ts
>      default:
if the aggregator is not defined in the task, we disregard the options altogether, that's unexcepted.

2024-07-22 10:24 UTC, tharvik commented on discojs/src/aggregator/mean.ts
> +    }
hum, warning instead of throwing when passed bad arguments feels icky. consider failing instead. we can always show it more nicely in the various user interfaces but the library itself shouldn't be too smart about it.

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/decentralized/base.ts
> +  private disconnected = false
`Client._server` (and `Client._ownID`) is undef when disconnected. consider reading it direclty or making a small helper `isDisconnected() { return this._server === undefined }`

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/decentralized/base.ts
> +      }
can this ever happen? we only wait for a single `PeersForRound` message from the server per round.

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/decentralized/base.ts
> +      }
consider moving it earlier, as this is only happening if the server isn't connected.

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/decentralized/base.ts
> +                peer.send(msg as messages.PeerMessage)
avoid cast if it can be. I'm now trying to comment everywhere I'm using `as` (bad keyword, bad)

you can instead have `const msg: messages.PeerMessage = …`

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/decentralized/base.ts
> +        console.error(e instanceof Error ? e.message : e)
```suggestion
        console.error(e)
```

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/decentralized/base.ts
> +      } catch (e) {
hum, so if this timeouts, we will still procede to the next communication round, but the payload will be invalid (already used by current round and very probably changed by it). I think breaking would be safer.

also, by creating the timeout in there, it is a timeout per communication round, not for the whole onRoundEnd, which is a bit unexcepted.

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/decentralized/peer.ts
> +    return this.bufferSize
soo, does this work? :eyes:

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/event_connection.ts
> +    ])
that's not our purview. if it's taking too long, we need to work on the wrtc stack itself. either with a documented upstream issue or even a PR.

```suggestion
    await this.peer.destroy()
```

2024-07-22 10:24 UTC, tharvik commented on discojs/src/client/federated/base.ts
> +  async receiveMetadataMap( // TODO: never used
clic clic, blast it

2024-07-22 10:24 UTC, tharvik commented on discojs/src/default_tasks/mnist.ts
> +        roundDuration: 2,
debug? it seems too frequent now.

2024-07-22 11:00 UTC, JulienVig commented on discojs/src/aggregator/mean.ts
> +    }
Indeed I'll throw exceptions. It's a remnant of a previous implementation where thresholdType had a default value.

2024-07-22 11:26 UTC, JulienVig commented on discojs/src/aggregator/get.ts
>      default:
Good catch, I'm changing this

2024-07-22 11:27 UTC, JulienVig commented on discojs/src/default_tasks/mnist.ts
> +        roundDuration: 2,
I don't think so, running the task in the webapp is still fast enough and I think that the more frequent the updates the better (if we can afford it time-wise)

2024-07-22 11:28 UTC, JulienVig commented on discojs/src/client/federated/base.ts
> +  async receiveMetadataMap( // TODO: never used
🫡

2024-07-22 11:42 UTC, JulienVig commented on discojs/src/client/decentralized/base.ts
> +      }
I don't think so, this is a copy paste from existing code. I'll remove it

2024-07-22 13:17 UTC, JulienVig commented on discojs/src/client/decentralized/peer.ts
> +    return this.bufferSize
At least on chrome it does. Do you know a way to test if it works reliably?

2024-07-22 13:24 UTC, JulienVig commented on discojs/src/client/decentralized/base.ts
> +      } catch (e) {
Ah yes I agree we should break/return here. However I don't see why a timeout per communication round is unexpected. Shouldn't we timeout whenever we may wait on a promise forever?

2024-07-22 14:15 UTC, tharvik commented on discojs/src/client/decentralized/base.ts
> +      } catch (e) {
> However I don't see why a timeout per communication round is unexpected. Shouldn't we timeout whenever we may wait on a promise forever?

yes, we should timeout for sure, but as each aggregator has a various number of communication round, the "onRoundEnd" timeout varies here which I find a bit weird. you can create the timeout promise at the beginning of the function and reference the same timeout in every communication round.
but yeah, maybe I'm overthinking this (won't be the first time), if you don't find it strange, let's keep it as it is (we don't really have a policy on timeouts anyway).

2024-07-22 14:22 UTC, tharvik commented on discojs/src/client/decentralized/peer.ts
> +    return this.bufferSize
meh, no, there are some services to try out with various browsers (cypress kinda does that) but testing two browsers communicating with each other is not easily provided.

2024-07-23 08:39 UTC, JulienVig commented on discojs/src/client/decentralized/peer.ts
> +    return this.bufferSize
Also works on safari and firefox (don't know how the previous ICEconnection issue got solved but it seems to be)
However it seems that using different browsers at the same time doesn't work, I get "connection closed" after they receive a contribution

2024-07-23 14:16 UTC, tharvik approved these changes

2024-07-23 14:35 UTC, merged