rework memory
epfml/disco pull request #764
Opened 2024-08-28 10:57 UTC by tharvik

* mv memory from discojs* to webapp
  * it's only used there and was more bothering than useful.
* rework memory store into models store, with persistence in local storage
* drop ModelLibrary side panel, now the only way to use stored models is via predict/test
  * drop downloading of model, which was only working for TFJS models (not for GPT, nor any other type of model). we can probably reintroduce it's use when we have a standard way to represent weights ([HDF5]?)(https://en.wikipedia.org/wiki/Hierarchical_Data_Format). if people want to access that anyway, they can do so using CLI/examples
* also fix model serialisation when crossing node & browser boundaries
* also add icon into button card

2024-08-28 15:17 UTC, martinjaggi commented
thanks a lot, looking excellent! model store or model library indeed are much better names than memory here

2024-08-29 16:46 UTC, JulienVig requested changes
Great job!! No more discojs memory!

* In the Testing page, clicking the next button displays an empty page. Maybe we should remove the next button to only allow going to the next page by clicking `Test` or `Predict`. (The title also displays `Model()`)
![Screenshot 2024-08-29 at 16 59 32](https://github.com/user-attachments/assets/5e2fb8e0-b0ea-430a-92ef-ff3ae366dd17)
* Training for a few epochs on Lus covid, stopping training and then saving the model display contradictory toasters. I guess we should be able to save the working model. Saving at the end of the training works great
![Screenshot 2024-08-29 at 18 39 30](https://github.com/user-attachments/assets/c4632818-a708-40a7-9b7e-ea80e36ce958)

2024-08-29 16:46 UTC, JulienVig commented on webapp/src/components/testing/Testing.vue
> +                  <button @click="removeModel(id)"><Bin2Icon /></button>
Very nice! A small hover feedback would be great
```suggestion
                  <button 
                    @click="removeModel(id)"
                    class="hover:text-red-500 transition duration-200"
                  >
                    <Bin2Icon />
                  </button>
```

2024-08-29 16:46 UTC, JulienVig commented on webapp/src/components/progress_bars/TestingBar.vue
>  const testing = computed(() => {
Related but not introduced by this PR: `testing` seems to be undefined when mounting the Testing page, so the TestingBar displays the title `Model ()`, it would be great to address the case when  `testing` is undefined more gracefully

2024-09-02 14:06 UTC, tharvik commented on webapp/src/components/testing/Testing.vue
> +                  <button @click="removeModel(id)"><Bin2Icon /></button>
hoo, that's so fancy, thanks for the tip!

2024-09-02 16:28 UTC, JulienVig approved these changes
All good thanks for your work!!

2024-09-04 09:41 UTC, merged