webapp: fix creation form
epfml/disco pull request #850
Opened 2024-12-19 11:12 UTC by tharvik

see #690 for context

* redo form
  * split into more categories
  * make it a bit nicer (no more loooong number input field)
  * greatly simplify fields implementation (no more type specific container, no dynamic form)
* rework the internal layout of many pages to better separate concerns

2025-02-12 11:26 UTC, JulienVig requested changes
Awesome work thank you for tackling the infamous creation form!
Okay I have a LOT of ideas, comments and two issues which I'll start with. Let's clearly choose what's reasonable to do in this PR and create an issue with future work :)

0. As mentioned in slack, the inference seems to be ~4x slower now with slight pauses every 10 images.
1. When submitting the form successfully (according to the toaster), I get the error `Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`. We should show a toaster error when something fails unexpectedly. Here are the values I used:
![Screenshot 2025-02-12 at 12 07 57](https://github.com/user-attachments/assets/259f87d0-3138-4fda-aa48-7010dd2bac41) 
![Screenshot 2025-02-12 at 12 08 06](https://github.com/user-attachments/assets/24b28e22-5ea9-40aa-980f-37d7896ecaec)
2. Note how in the previous screenshot the width and height fields are not fully responsive
3. I would like to add some explanation for each field, maybe when hovering over an "i" or "?" icon as @tomasoignons had implemented, I'm happy to help writing some descriptions if you want.
4. I think we need to add more information for the model.json field, for example explain what is "TFJS", why we are using tensorflow.js, linking tfjs docs, where do download pre-trained models etc
5. I suggest changing "Category of data" to "Data type"
6. I think there should be a learning rate field in the model section, this is quite important and depends on the data, loss and model architecture
7. Are we validating that the loss and optimizer input by the user exist in tfjs?
8. "Number of pass over the data" ⇾ "Epochs" (and "Number of **passes** over the data" on hover). So that we use conventional names
9. "Number of dataset element to process at once" ⇾ "Batch size" (with "Number of dataset elements to process at once" on hover)
10. "Kind of network to run on" ⇾ "Collaborative algorithm"?
11. "Number of epoch before exchanging with the network" ⇾ "Number of **epochs** before exchanging with the network" 
12. Can you add asterisks or another marker on questions that are required? (and potentially writing "optional" for questions that are not) Right now we need to test each field individually to see which ones are required
13. Can we make error messages more user-friendly like "Please choose an image type"? Would it be possible to make the page scroll to the error when clicking submit? If too complicated can we print an error above/below the submit button? Otherwise there is no UI feedback when the error is outside the screen
![Screenshot 2025-02-12 at 10 48 37](https://github.com/user-attachments/assets/1b643de3-0f3c-4b26-9944-c8361ec6048a)
14. Should we create the unique identifier ourselves instead? Are we even checking that it is unique when a user submits a new task?
15. Regarding Differential Privacy it's not clear that leaving fields blank doesn't use DP, I think we should first ask whether to use DP and if yes ask for values (and make the fields required)
16. I don't think anyone can pick a good value for "Maximum weights difference between each round"... Does it need a unit or naming how the difference is computed (e.g. "per Euclidean distance")?
17. What is the "Size of the noise added to the weights"?
18. "Secure" aggregation is currently only available for Decentralized learning
19. Idem for "Secure Aggregation". Additionally it should only be available when choosing Decentralized Learning and "secure" aggregation type
20. Should "Maximum value of a single weight" be max absolute value or maximum magnitude? It's not clear to me if weight is a scalar, a vector or a tensor, isn't DP clipping the gradient rather than single weight values?
21. I notice small indents after "Differential Privacy" and "Secure Aggregations" but I don't think it's clear enough that these are headings, consider making the headings' font size bigger rather than adding an indent
22. "Expected data format" has placeholder "Images with [...]" even if the current data type is "tabular" or "text". Anyway I think this fields is more about accepted file format (e.g. for images we accept png jpeg and jpg, tabular only csv, etc) than the data content, isn't it? Though we can add both accepted file extensions and what data should look like.
23. "How to join after ?" I think having to explain this denotes that we're doing something wrong that isn't intuitive enough. But if we keep it I'd write it "Joining this task". For example (and probably future work) clicking submit successfully could go to a new page with "Your tasks has been created successfully", and two buttons: "Share this task" with a permalink and "Go to the task".
24. When clicking submit and form validation succeeds, rather than a toaster we should show a loading indicator with "Creating the task..."
25. Refreshing the page empties out the fields which can be annoying. Can we either persist them or have the browser confirm that we want to leave this page?
26. For future work, after successfully filling the form we could have the user connect data and train a model locally for a few epochs to make sure that labels, image dimensions, and would let the user see if the learning rate is okay, if the loss is adequate or diverges etc (so let them go back and forth between the form and the sample training until final validation and uploading the task)
27. For future work, it would be useful to have a preview of how the task would look like as the user fills the task title, description, sample data url etc before final validation.
28. For future work I was thinking of making the form a succession of pages rather than having everything in one page, it would make the experience smoother and less daunting and would hide how choosing the data type changes subsequent questions. I'm attaching a random example that I think looks nice:

https://github.com/user-attachments/assets/37d1eb17-1c17-411b-acd1-95a6da662ac1

2025-02-12 11:26 UTC, JulienVig commented on server/src/routes/training_router.ts
> -    })
No more `process.nextTick` 🎉

2025-07-31 21:14 UTC, tharvik commented
that's finally it :tada: most comments handled, the remaining is sitting at #921 to do another time.
this is a **huge** PR, sorry about that, this hopefully cleanups up a lot of misc issues/improvements that has been staying in the back of my mind. a cleaner setup for a new semester (and a new release before that :rocket:)

2025-08-13 13:29 UTC, JulienVig requested changes
I haven't looked at everything yet but it already looks much better! 
I've encountered a few errors while trying to create tasks so I'm reporting them right away before I start going through the code.

2025-08-13 13:29 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +              </FormLabel>
Same here, a dropdown menu would make more sense

2025-08-13 13:29 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +              >
Can we make this a dropdown menu with only the available optimizers as options? This avoids typos and having to lookup the TFJS documentation.

2025-08-13 13:29 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +      if (!(file instanceof File))
1. I get an error here when trying to drag and drop titanic's model.json (no error if I click on the button to choose the file). If I print what `file` is when drag and dropping, here is what I get:
```js
Object { size: 1, _map: {…}, __ownerID: undefined }​
__ownerID: undefined​
_map: Object { size: 1, _root: {…}, __altered: false, … }​​
__altered: false​​
__hash: undefined​​
__ownerID: undefined​​
_root: Object { ownerID: {}, entries: (1) […] }​​​
entries: Array [ (2) […] ]​​​​
0: Array [ File, File ]​​​​​
0: File { name: "model.json", lastModified: 1755078810962, size: 45623, … }​​​​​​
lastModified: 1755078810962​​​​​​
name: "model.json"​​​​​​
size: 45623​​​​​​
type: "application/json"​​​​​​
webkitRelativePath: ""​​​​​​
<prototype>: FilePrototype { name: Getter, lastModified: Getter, webkitRelativePath: Getter, … }​​​​​
1: File { name: "model.json", lastModified: 1755078810962, size: 45623, … }​​​​​
length: 2​​​​​
<prototype>: Array []​​​​
length: 1​​​​
<prototype>: Array []​​​
ownerID: Object { }
<prototype>: Object { get: get2(shift, keyHash, key, notSetValue), update: update2(ownerID, shift, keyHash, key, value, didChangeSize, didAlter), iterate: iterate(fn, reverse3), … }
size: 1
<prototype>: Object { constructor: Map2(value), toString: toString5(), get: get11(k, notSetValue), … }
size: 1
<prototype>: Object { constructor: Set2(value), toString: toString5(), has: has5(value), … }
```

2. when I upload the file by clicking on the upload button and choose the file I don't get an error here but one later on when I submit (´Model file isn't valid`), cf comment l.771

2025-08-13 13:29 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +      if (!(file instanceof File))
Should we also add a toaster error here?

2025-08-13 13:29 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +      modelOptimizerNames[6];
There're only 6 values in this array, why silence the typescript error on a 7th element? I see that the momentum optimizer was commented out, maybe there was a confusion on the total number of elements at some point

2025-08-13 13:29 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +            </FormField>
When I select a data type, "Missing dependant fields" immediately shows up underneath. I need to enter all required values after that to make this error disappear.
1. The type of aggregation is not a required field but an error if I don't choose it, I guess we can either make "mean" the default value or make the field required.
2. Since required fields already show an error when missing can we remove the "missing dependant fields" error? (A consequence of having two errors for one missing field is that clicking submit scrolls to the first error which is the data type with "Missing dependant field" rather than the actual missing field and I find this confusing)

2025-08-13 13:29 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +  }
When I upload any model.json among titanic, COVID or LLM task, I get the error: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`. Did you manage to successfully upload a model?

2025-08-22 11:06 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +              >
good idea! I got used to it but that's clearly more user friendly

2025-08-22 11:09 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +      if (!(file instanceof File))
no, the user can't input smth else as this value is coming from our component so nothing they can do about it to fix it

2025-08-22 11:21 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +      modelOptimizerNames[6];
yeah, that's a typescript trick I'm using to ensure that the switch is correctly checking for all the values inside the array. if a new value is added to the array, it will fail to compile until this switch is changed. it's setting a consistency trap for later if you will

2025-08-26 10:43 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +      if (!(file instanceof File))
arf, yeah, I'm unable to find the actual source of the bug, probably some weird behavior that vee-validate is doing. working around that

2025-08-26 11:18 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +  }
I think you are uploading the `model.json` we store on the server, no? its format is actually our own serialized version and not a TFJS model encoding. yeah, that's confusing..
you can get a "classic" model.json there https://storage.googleapis.com/tfjs-models/tfjs/iris_v1/model.json

2025-08-26 11:37 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +            </FormField>
> When I select a data type, "Missing dependant fields" immediately shows up underneath. I need to enter all required values after that to make this error disappear.
> Since required fields already show an error when missing can we remove the "missing dependant fields" error?

yeah, that's indeed bothering; moving to supress this error (and it's indeed nicer!)

> 1. The type of aggregation is not a required field but an error if I don't choose it, I guess we can either make "mean" the default value or make the field required.

making it both required and starting with "mean"

2025-09-15 10:34 UTC, JulienVig approved these changes
The form is working great!! I left some minor comments but nothing blocking.

1. If it's easy it would be great if successfully submitting a task takes you to the task list (and resets the creation form), right now it just shows a toaster without anything else which made me wonder if it actually worked
2. Once the PR is merged, created tasks will get deleted at every server reboot right? Did you have something in mind about this?
3. If we implement something to keep tasks permanently, we'll probably have to also have a way to remove some of them.

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/dataset_input/FileSelection.vue
> +    private?: boolean; // file stays in browser
"file stays in browser" makes it sound like setting private=False will upload the data. Can we replace the prop by lockIcon?: boolean for example?

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/dataset_input/FileSelection.vue
> +}>();
I guess from the commit title that vee-validate expects 'blur' events from custom components, could you add some comments with more info on this event and maybe some pointers to the vee documentation?

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/training/TrainerDashboard.vue
> +            class="flex flex-col gap-y-4 min-w-full lg:min-w-[42rem]"
I think this css change de-centered the toggle button
<img width="663" height="270" alt="Screenshot 2025-08-13 at 17 14 04" src="https://github.com/user-attachments/assets/8245704e-f996-4eab-937d-8b6cd1d3806a" />

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +                  step="0.01"
Can we remove the step parameter? I don't think we need to constrain user input here. I sometimes use learn rates down to 1e-7.
We should exclude 0 too, so somthing like gt=0

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +    else toaster.error("An error occured server-side");
One day we'll have a better framework for error handling #677 ...

2025-09-15 10:34 UTC, JulienVig commented on discojs/src/task/task.ts
> +export namespace Task {
Maybe directly merge the two `Task` namespaces

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +              label="Number of epochs before exchanging with the network"
```suggestion
              label="Number of epochs before aggregating weights"
```
Since we're saying "Type of aggregation" in the previous field we might as well re-use the same language I think?

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +            <FormLabel label="Type of aggregation to perform" type="required">
```suggestion
            <FormLabel label="Type of aggregation" type="required">
```

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +                  <CustomButton @click="push('')"> add label </CustomButton>
The Add Label button's actual size doesn't match its visual

https://github.com/user-attachments/assets/bea1665f-36f7-4ec0-bfa7-42b10e171fbc

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +                  <CustomButton @click="push('')"> add column </CustomButton>
Same here, the actual clickable zone is bigger than the button's visual

2025-09-15 10:34 UTC, JulienVig commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +              </FormField>
If it's easy it would make sense I think to omit this field when there's only a single option (federated only allows mean aggregation). I think having a field with a single option is a bit weird/confusing but it's not a big deal if that's time-consuming to implement

2025-09-18 15:12 UTC, tharvik commented on webapp/src/components/training/TrainerDashboard.vue
> +            class="flex flex-col gap-y-4 min-w-full lg:min-w-[42rem]"
haa yes, well spotted!

2025-09-19 21:51 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +                  <CustomButton @click="push('')"> add label </CustomButton>
yeah, that's a bit weird indeed. I looked into it a bit and I found the rational behind it: as I'm using `<label>` to wrap every field, and when interacting with it it behave as if you interacted with the field directly. the rational from the W3C is for accessibility https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/label#usage_notes

now, to get the best of both world, we can start with a empty label already created, and so having two buttons, delete and add, so it won't move to one on hover (and is also more explicit that it needs at least one label)

2025-09-23 11:07 UTC, tharvik commented on webapp/src/components/task_creation_form/TaskCreationForm.vue
> +              </FormField>
removing the field proved more complicated then expected. disabling the field instead.

2025-09-23 11:18 UTC, tharvik commented
> 1. If it's easy it would be great if successfully submitting a task takes you to the task list (and resets the creation form), right now it just shows a toaster without anything else which made me wonder if it actually worked

great idea! added

> 2. Once the PR is merged, created tasks will get deleted at every server reboot right? Did you have something in mind about this?

right, for now, I'm telling myself that it's okay as it's only a demo (and it's already the case). persistence can be added and would prove useful for sure!

> 3. If we implement something to keep tasks permanently, we'll probably have to also have a way to remove some of them.

yeah, that'd make sense, but allowing anyone to remove a task (as we don't have an user identification system) seems wrong. I'm maybe over thinking this and we might just allow that, and regularly restore it to a know good state (i.e. our default task list)

anyway, thanks for the multiple reviews, that helped to have another look at it! I'm currently rebasing everything and checking that each commit works but soon, very soon, we'll have it merged :tada: finally :mirror_ball:

2025-09-24 11:34 UTC, merged